# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # Box Settings #
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "yrimahS"

  # Provider Settings #
  config.vm.provider "virtualbox" do |vb|
  
    vb.memory = 8024
    vb.cpus = 4
    vb.name = "yrimahS"
  end

  # Network Settings #
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.56.4"

end
